### ISSUE TITLE
Links still pointing to fisherman's page

### ISSUE THREAD

**Issue by shaqman** [argos-scripts/argos-scripts.github.io#1]
These links on the top page need to be removed or changed to point an argos.

**Comment by shaqman** [comment]
@Hippyjake Yeah, lets continue on here.
I am a bit good in javascript, so I could help. I haven't used Jekyll before though, so it might take some time for me to get started.

**Comment by Hippyjake** [comment]
Its easy to get started. I have a little script, if you want ill put it in the repo

**Comment by Hippyjake** [comment]
Ok changes are pushed. 

To use the script `./tester.sh w` The "w" open a web page. dont mind my bad bash script ha.
